movieapp/urls.py
from django.urls import path
from movieapp import views
app_name='movieapp'
urlpatterns = [
   path('', views.index, name='index'),
  path('movie/<int:movie_id>/',views.details,name='details'),
 path('add/',views.add_movie,name='add_movie'),

   path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movieproject/urls.py
from django.contrib import admin
from django.urls import path, include

from movieproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=50)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name

movieapp/forms.py
from django import forms
from . models import Movie
class movieform (forms.ModelForm):
    class Meta:
        model=Movie
        fields=('name','desc','year','img')

movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from movieapp.models import Movie
from . forms import movieform
# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={'movie_list':movie}
    return render(request,'index.html',context)
def details(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,'details.html',{'movie':movie})
def add_movie(request):
    if request.method=="POST":
        name1=request.POST.get('name',)
        desc1=request.POST.get('desc',)
        year1=request.POST.get('year',)
        img1=request.FILES['img']
        movie=Movie(name=name1,desc=desc1,year=year1,img=img1)
        movie.save()


    return render(request, 'add.html')

def update(request,id):
    movie = Movie.objects.get(id=id)
    form=movieform(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form1':form,'movie1':movie})

def delete(request,id):
    if request.method=="POST":
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')




# def delete(request, id):
#     movie = Movie.objects.get(id=id)
#
#     if request.method == "POST":
#         if "yes" in request.POST:
#             movie.delete()
#             return redirect('/')
#         else:
#             return redirect('/')
#
#     return render(request, 'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" enctype="multipart/form-data"><br>
{% csrf_token %}
<input type="text" name="name" placeholder="Enter movie name "><br>
<input type="text" name="desc" placeholder="Enter description "><br>
<input type="text" name="year" placeholder="Enter year "><br>
<input type="file" name="img"><br>
<input type="submit">

<a href="{% url 'movieapp:index' %}" class="index_button">Back to home</a><br>
<button class="add-button" onclick="window.location.href='{% url 'movieapp:index' %}'">Back to home</button>
</form>
</body>
</html>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
movies
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{form1.as_p}}
    Are you ready to delete?<br>
    <input type="submit" value="yes">

</form>
{% endblock %}

templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">

        </div>
        <div class="col-md-6">
            <h6>{{movie.name}}<br></h6>
            <h6>{{movie.year}}<br></h6>
            <h3>{{movie.desc}}<br></h3>

<a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
<a class="btn btn-warning" href="{% url 'movieapp:delete' movie.id %}">Delete</a>

        </div>
    </div>
</div>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{form1.as_p}}
    <input type="submit">
</form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}



<div class="container">
   <div class="row">
       {% for i in movie_list %}
       <div class="col-md-3">
           <div class="card" style="width: 18rem;">
                <img src="{{i.img.url}}" class="card-img-top" alt="Card image cap" width="100" height="300">
                <div class="card-body">
                   <h5 class="card-title">{{i.name}}</h5>
                   <p class="card-text">{{i.desc}}</p>
                    <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">View details</a>
        </div>
    </div>

       </div>
         {% endfor %}
   </div>
</div>
<a href="{% url 'movieapp:add_movie' %}" class="add-button">Add Movie</a><br>
<button class="add-button" onclick="window.location.href='{% url 'movieapp:add_movie' %}'">Add Movie</button>
{% endblock %}

<!--<a href="movie/{{i.id}}">{{i.name}}<br>-->
<!--<img src="{{i.img.url}}" width="100" height="100">-->
<!--<a href="{% url 'movieapp:details' i.id %}">{{i.name}}<br>-->